package entity;
// Generated 2016-12-17 23:35:50 by Hibernate Tools 5.1.0.Beta1

/**
 * AllPayrecord generated by hbm2java
 */
public class AllPayrecord implements java.io.Serializable {

	private AllPayrecordId id;

	public AllPayrecord() {
	}

	public AllPayrecord(AllPayrecordId id) {
		this.id = id;
	}

	public AllPayrecordId getId() {
		return this.id;
	}

	public void setId(AllPayrecordId id) {
		this.id = id;
	}

}
