package entity;
// Generated 2016-12-17 23:35:50 by Hibernate Tools 5.1.0.Beta1

/**
 * AllPayrecordId generated by hbm2java
 */
public class AllPayrecordId implements java.io.Serializable {

	private String payer;
	private double payMoney;
	private String payWay;
	private String payAccount;
	private int id;
	private String vicePayer;
	private String receiver;
	private String connPerson;
	private String linkCer;
	private Integer bankinputId;
	private String owner;
	private Character checkResult;
	private Byte pass;
	private Byte isconnect;
	private String manyPay;
	private String uploadTime;
	private String contractNum;
	private String caid;
	private Byte freeback;
	private String actualPayer;
	private String paymentNature;
	private String actualPayTime;

	public AllPayrecordId() {
	}

	public AllPayrecordId(String payer, double payMoney, String payWay, int id) {
		this.payer = payer;
		this.payMoney = payMoney;
		this.payWay = payWay;
		this.id = id;
	}

	public AllPayrecordId(String payer, double payMoney, String payWay, String payAccount, int id, String vicePayer,
			String receiver, String connPerson, String linkCer, Integer bankinputId, String owner,
			Character checkResult, Byte pass, Byte isconnect, String manyPay, String uploadTime, String contractNum,
			String caid, Byte freeback, String actualPayer, String paymentNature, String actualPayTime) {
		this.payer = payer;
		this.payMoney = payMoney;
		this.payWay = payWay;
		this.payAccount = payAccount;
		this.id = id;
		this.vicePayer = vicePayer;
		this.receiver = receiver;
		this.connPerson = connPerson;
		this.linkCer = linkCer;
		this.bankinputId = bankinputId;
		this.owner = owner;
		this.checkResult = checkResult;
		this.pass = pass;
		this.isconnect = isconnect;
		this.manyPay = manyPay;
		this.uploadTime = uploadTime;
		this.contractNum = contractNum;
		this.caid = caid;
		this.freeback = freeback;
		this.actualPayer = actualPayer;
		this.paymentNature = paymentNature;
		this.actualPayTime = actualPayTime;
	}

	public String getPayer() {
		return this.payer;
	}

	public void setPayer(String payer) {
		this.payer = payer;
	}

	public double getPayMoney() {
		return this.payMoney;
	}

	public void setPayMoney(double payMoney) {
		this.payMoney = payMoney;
	}

	public String getPayWay() {
		return this.payWay;
	}

	public void setPayWay(String payWay) {
		this.payWay = payWay;
	}

	public String getPayAccount() {
		return this.payAccount;
	}

	public void setPayAccount(String payAccount) {
		this.payAccount = payAccount;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getVicePayer() {
		return this.vicePayer;
	}

	public void setVicePayer(String vicePayer) {
		this.vicePayer = vicePayer;
	}

	public String getReceiver() {
		return this.receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	public String getConnPerson() {
		return this.connPerson;
	}

	public void setConnPerson(String connPerson) {
		this.connPerson = connPerson;
	}

	public String getLinkCer() {
		return this.linkCer;
	}

	public void setLinkCer(String linkCer) {
		this.linkCer = linkCer;
	}

	public Integer getBankinputId() {
		return this.bankinputId;
	}

	public void setBankinputId(Integer bankinputId) {
		this.bankinputId = bankinputId;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public Character getCheckResult() {
		return this.checkResult;
	}

	public void setCheckResult(Character checkResult) {
		this.checkResult = checkResult;
	}

	public Byte getPass() {
		return this.pass;
	}

	public void setPass(Byte pass) {
		this.pass = pass;
	}

	public Byte getIsconnect() {
		return this.isconnect;
	}

	public void setIsconnect(Byte isconnect) {
		this.isconnect = isconnect;
	}

	public String getManyPay() {
		return this.manyPay;
	}

	public void setManyPay(String manyPay) {
		this.manyPay = manyPay;
	}

	public String getUploadTime() {
		return this.uploadTime;
	}

	public void setUploadTime(String uploadTime) {
		this.uploadTime = uploadTime;
	}

	public String getContractNum() {
		return this.contractNum;
	}

	public void setContractNum(String contractNum) {
		this.contractNum = contractNum;
	}

	public String getCaid() {
		return this.caid;
	}

	public void setCaid(String caid) {
		this.caid = caid;
	}

	public Byte getFreeback() {
		return this.freeback;
	}

	public void setFreeback(Byte freeback) {
		this.freeback = freeback;
	}

	public String getActualPayer() {
		return this.actualPayer;
	}

	public void setActualPayer(String actualPayer) {
		this.actualPayer = actualPayer;
	}

	public String getPaymentNature() {
		return this.paymentNature;
	}

	public void setPaymentNature(String paymentNature) {
		this.paymentNature = paymentNature;
	}

	public String getActualPayTime() {
		return this.actualPayTime;
	}

	public void setActualPayTime(String actualPayTime) {
		this.actualPayTime = actualPayTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AllPayrecordId))
			return false;
		AllPayrecordId castOther = (AllPayrecordId) other;

		return ((this.getPayer() == castOther.getPayer()) || (this.getPayer() != null && castOther.getPayer() != null
				&& this.getPayer().equals(castOther.getPayer())))
				&& (this.getPayMoney() == castOther.getPayMoney())
				&& ((this.getPayWay() == castOther.getPayWay()) || (this.getPayWay() != null
						&& castOther.getPayWay() != null && this.getPayWay().equals(castOther.getPayWay())))
				&& ((this.getPayAccount() == castOther.getPayAccount()) || (this.getPayAccount() != null
						&& castOther.getPayAccount() != null && this.getPayAccount().equals(castOther.getPayAccount())))
				&& (this.getId() == castOther.getId())
				&& ((this.getVicePayer() == castOther.getVicePayer()) || (this.getVicePayer() != null
						&& castOther.getVicePayer() != null && this.getVicePayer().equals(castOther.getVicePayer())))
				&& ((this.getReceiver() == castOther.getReceiver()) || (this.getReceiver() != null
						&& castOther.getReceiver() != null && this.getReceiver().equals(castOther.getReceiver())))
				&& ((this.getConnPerson() == castOther.getConnPerson()) || (this.getConnPerson() != null
						&& castOther.getConnPerson() != null && this.getConnPerson().equals(castOther.getConnPerson())))
				&& ((this.getLinkCer() == castOther.getLinkCer()) || (this.getLinkCer() != null
						&& castOther.getLinkCer() != null && this.getLinkCer().equals(castOther.getLinkCer())))
				&& ((this.getBankinputId() == castOther.getBankinputId())
						|| (this.getBankinputId() != null && castOther.getBankinputId() != null
								&& this.getBankinputId().equals(castOther.getBankinputId())))
				&& ((this.getOwner() == castOther.getOwner()) || (this.getOwner() != null
						&& castOther.getOwner() != null && this.getOwner().equals(castOther.getOwner())))
				&& ((this.getCheckResult() == castOther.getCheckResult())
						|| (this.getCheckResult() != null && castOther.getCheckResult() != null
								&& this.getCheckResult().equals(castOther.getCheckResult())))
				&& ((this.getPass() == castOther.getPass()) || (this.getPass() != null && castOther.getPass() != null
						&& this.getPass().equals(castOther.getPass())))
				&& ((this.getIsconnect() == castOther.getIsconnect()) || (this.getIsconnect() != null
						&& castOther.getIsconnect() != null && this.getIsconnect().equals(castOther.getIsconnect())))
				&& ((this.getManyPay() == castOther.getManyPay()) || (this.getManyPay() != null
						&& castOther.getManyPay() != null && this.getManyPay().equals(castOther.getManyPay())))
				&& ((this.getUploadTime() == castOther.getUploadTime()) || (this.getUploadTime() != null
						&& castOther.getUploadTime() != null && this.getUploadTime().equals(castOther.getUploadTime())))
				&& ((this.getContractNum() == castOther.getContractNum())
						|| (this.getContractNum() != null && castOther.getContractNum() != null
								&& this.getContractNum().equals(castOther.getContractNum())))
				&& ((this.getCaid() == castOther.getCaid()) || (this.getCaid() != null && castOther.getCaid() != null
						&& this.getCaid().equals(castOther.getCaid())))
				&& ((this.getFreeback() == castOther.getFreeback()) || (this.getFreeback() != null
						&& castOther.getFreeback() != null && this.getFreeback().equals(castOther.getFreeback())))
				&& ((this.getActualPayer() == castOther.getActualPayer())
						|| (this.getActualPayer() != null && castOther.getActualPayer() != null
								&& this.getActualPayer().equals(castOther.getActualPayer())))
				&& ((this.getPaymentNature() == castOther.getPaymentNature())
						|| (this.getPaymentNature() != null && castOther.getPaymentNature() != null
								&& this.getPaymentNature().equals(castOther.getPaymentNature())))
				&& ((this.getActualPayTime() == castOther.getActualPayTime())
						|| (this.getActualPayTime() != null && castOther.getActualPayTime() != null
								&& this.getActualPayTime().equals(castOther.getActualPayTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPayer() == null ? 0 : this.getPayer().hashCode());
		result = 37 * result + (int) this.getPayMoney();
		result = 37 * result + (getPayWay() == null ? 0 : this.getPayWay().hashCode());
		result = 37 * result + (getPayAccount() == null ? 0 : this.getPayAccount().hashCode());
		result = 37 * result + this.getId();
		result = 37 * result + (getVicePayer() == null ? 0 : this.getVicePayer().hashCode());
		result = 37 * result + (getReceiver() == null ? 0 : this.getReceiver().hashCode());
		result = 37 * result + (getConnPerson() == null ? 0 : this.getConnPerson().hashCode());
		result = 37 * result + (getLinkCer() == null ? 0 : this.getLinkCer().hashCode());
		result = 37 * result + (getBankinputId() == null ? 0 : this.getBankinputId().hashCode());
		result = 37 * result + (getOwner() == null ? 0 : this.getOwner().hashCode());
		result = 37 * result + (getCheckResult() == null ? 0 : this.getCheckResult().hashCode());
		result = 37 * result + (getPass() == null ? 0 : this.getPass().hashCode());
		result = 37 * result + (getIsconnect() == null ? 0 : this.getIsconnect().hashCode());
		result = 37 * result + (getManyPay() == null ? 0 : this.getManyPay().hashCode());
		result = 37 * result + (getUploadTime() == null ? 0 : this.getUploadTime().hashCode());
		result = 37 * result + (getContractNum() == null ? 0 : this.getContractNum().hashCode());
		result = 37 * result + (getCaid() == null ? 0 : this.getCaid().hashCode());
		result = 37 * result + (getFreeback() == null ? 0 : this.getFreeback().hashCode());
		result = 37 * result + (getActualPayer() == null ? 0 : this.getActualPayer().hashCode());
		result = 37 * result + (getPaymentNature() == null ? 0 : this.getPaymentNature().hashCode());
		result = 37 * result + (getActualPayTime() == null ? 0 : this.getActualPayTime().hashCode());
		return result;
	}

}
