package entity;
// Generated 2016-12-17 23:35:50 by Hibernate Tools 5.1.0.Beta1

/**
 * Backup generated by hbm2java
 */
public class Backup implements java.io.Serializable {

	private Integer id;
	private String filename;

	public Backup() {
	}

	public Backup(String filename) {
		this.filename = filename;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

}
