package entity;
// Generated 2016-12-1 21:09:21 by Hibernate Tools 5.1.0.Beta1

/**
 * CusSdstoreBackup generated by hbm2java
 */
public class CusSdstoreBackup implements java.io.Serializable {

	private String client;
	private Double input;
	private String updateTime;
	private String contractMes;
	private Integer contractNum;
	private String owner;
	private Integer total;
	private String accoutMes;

	public CusSdstoreBackup() {
	}

	public CusSdstoreBackup(String client) {
		this.client = client;
	}

	public CusSdstoreBackup(String client, Double input, String updateTime, String contractMes, Integer contractNum,
			String owner, Integer total, String accoutMes) {
		this.client = client;
		this.input = input;
		this.updateTime = updateTime;
		this.contractMes = contractMes;
		this.contractNum = contractNum;
		this.owner = owner;
		this.total = total;
		this.accoutMes = accoutMes;
	}

	public String getClient() {
		return this.client;
	}

	public void setClient(String client) {
		this.client = client;
	}

	public Double getInput() {
		return this.input;
	}

	public void setInput(Double input) {
		this.input = input;
	}

	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	public String getContractMes() {
		return this.contractMes;
	}

	public void setContractMes(String contractMes) {
		this.contractMes = contractMes;
	}

	public Integer getContractNum() {
		return this.contractNum;
	}

	public void setContractNum(Integer contractNum) {
		this.contractNum = contractNum;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	public String getAccoutMes() {
		return this.accoutMes;
	}

	public void setAccoutMes(String accoutMes) {
		this.accoutMes = accoutMes;
	}

}
