package entity;
// Generated 2016-12-7 20:55:28 by Hibernate Tools 5.1.0.Beta1

/**
 * OriOrderBackupId generated by hbm2java
 */
public class OriOrderBackupId implements java.io.Serializable {

	private String cuscompanyid;
	private String paymentNature;

	public OriOrderBackupId() {
	}

	public OriOrderBackupId(String cuscompanyid, String paymentNature) {
		this.cuscompanyid = cuscompanyid;
		this.paymentNature = paymentNature;
	}

	public String getCuscompanyid() {
		return this.cuscompanyid;
	}

	public void setCuscompanyid(String cuscompanyid) {
		this.cuscompanyid = cuscompanyid;
	}

	public String getPaymentNature() {
		return this.paymentNature;
	}

	public void setPaymentNature(String paymentNature) {
		this.paymentNature = paymentNature;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OriOrderBackupId))
			return false;
		OriOrderBackupId castOther = (OriOrderBackupId) other;

		return ((this.getCuscompanyid() == castOther.getCuscompanyid()) || (this.getCuscompanyid() != null
				&& castOther.getCuscompanyid() != null && this.getCuscompanyid().equals(castOther.getCuscompanyid())))
				&& ((this.getPaymentNature() == castOther.getPaymentNature())
						|| (this.getPaymentNature() != null && castOther.getPaymentNature() != null
								&& this.getPaymentNature().equals(castOther.getPaymentNature())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCuscompanyid() == null ? 0 : this.getCuscompanyid().hashCode());
		result = 37 * result + (getPaymentNature() == null ? 0 : this.getPaymentNature().hashCode());
		return result;
	}

}
