package entity;
// Generated 2016-12-9 19:45:29 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * ScoreExchangeRecord generated by hbm2java
 */
public class ScoreExchangeRecord implements java.io.Serializable {

	private Integer id;
	private String username;
	private Integer exchangeScore;
	private Byte exchangeType;
	private Byte status;
	private Date applicaTime;
	private Date finishTime;
	private Date serialNumber;
	private String randkey;
	private String description;
	private String hander;

	public ScoreExchangeRecord() {
	}

	public ScoreExchangeRecord(String username, Integer exchangeScore, Byte exchangeType, Byte status, Date applicaTime,
			Date finishTime, Date serialNumber, String randkey, String description, String hander) {
		this.username = username;
		this.exchangeScore = exchangeScore;
		this.exchangeType = exchangeType;
		this.status = status;
		this.applicaTime = applicaTime;
		this.finishTime = finishTime;
		this.serialNumber = serialNumber;
		this.randkey = randkey;
		this.description = description;
		this.hander = hander;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getExchangeScore() {
		return this.exchangeScore;
	}

	public void setExchangeScore(Integer exchangeScore) {
		this.exchangeScore = exchangeScore;
	}

	public Byte getExchangeType() {
		return this.exchangeType;
	}

	public void setExchangeType(Byte exchangeType) {
		this.exchangeType = exchangeType;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Date getApplicaTime() {
		return this.applicaTime;
	}

	public void setApplicaTime(Date applicaTime) {
		this.applicaTime = applicaTime;
	}

	public Date getFinishTime() {
		return this.finishTime;
	}

	public void setFinishTime(Date finishTime) {
		this.finishTime = finishTime;
	}

	public Date getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(Date serialNumber) {
		this.serialNumber = serialNumber;
	}

	public String getRandkey() {
		return this.randkey;
	}

	public void setRandkey(String randkey) {
		this.randkey = randkey;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getHander() {
		return this.hander;
	}

	public void setHander(String hander) {
		this.hander = hander;
	}

}
