package entity;
// Generated 2016-12-1 21:09:21 by Hibernate Tools 5.1.0.Beta1

/**
 * WeixinBindAssistance generated by hbm2java
 */
public class WeixinBindAssistance implements java.io.Serializable {

	private String username;
	private String weixinid;

	public WeixinBindAssistance() {
	}

	public WeixinBindAssistance(String username) {
		this.username = username;
	}

	public WeixinBindAssistance(String username, String weixinid) {
		this.username = username;
		this.weixinid = weixinid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getWeixinid() {
		return this.weixinid;
	}

	public void setWeixinid(String weixinid) {
		this.weixinid = weixinid;
	}

}
