package entity;
// Generated 2016-12-26 13:35:33 by Hibernate Tools 5.1.0.Beta1

/**
 * WeixinBindConnectPerson generated by hbm2java
 */
public class WeixinBindConnectPerson implements java.io.Serializable {

	private String username;
	private String weixinid;

	public WeixinBindConnectPerson() {
	}

	public WeixinBindConnectPerson(String username) {
		this.username = username;
	}

	public WeixinBindConnectPerson(String username, String weixinid) {
		this.username = username;
		this.weixinid = weixinid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getWeixinid() {
		return this.weixinid;
	}

	public void setWeixinid(String weixinid) {
		this.weixinid = weixinid;
	}

}
